spring:
  application:
    name: Provincia
  datasource:
    url: jdbc:h2:mem:provincia
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform:
      hibernate:
        dialect: H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

accuweather:
  host:
    cities: http://dataservice.accuweather.com/locations/v1/cities/search?apikey=%s&q=%s
    weather: http://dataservice.accuweather.com/forecasts/v1/daily/1day/%d?apikey=%s

server:
  port: 8080
  servlet:
    context-path: /Provincia
